cpu-bind=MASK - cortado, task  0  0 [2288426]: mask 0xff00000000ff00000000 set
Traceback (most recent call last):
  File "/data/healthy-ml/scratch/abinitha/craft-md/craft-md/script.py", line 27, in <module>
    dataset = pd.read_csv('craft-md/data_augmented/baseline.csv')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/detect/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/detect/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/detect/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/detect/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/detect/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'craft-md/data_augmented/baseline.csv'
